[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Custom derive required by the relm crate."
documentation = "https://docs.rs/relm-derive/"
license = "MIT"
name = "relm-derive"
repository = "https://github.com/antoyo/relm"
version = "0.1.3-pre"

[lib]
proc-macro = true

[dependencies]
quote = "^0.3.14"
relm-gen-widget = "^0.1.0"
syn = "^0.11.8"
