[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Common derive implementation internally used by relm crates"
license = "MIT"
name = "relm-derive-common"
repository = "https://github.com/antoyo/relm"
version = "0.11.0"

[dependencies]
quote = "^0.3.15"
syn = "^0.11.11"

[dependencies.relm-gen-widget]
path = "../relm-gen-widget"
version = "^0.11.0"
