[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "relm"
version = "0.1.0"

[dependencies]
futures = "^0.1.10"
gtk = "^0.1.1"

[dependencies.relm-core]
path = "relm-core"

[dev-dependencies]
tokio-core = "^0.1.4"
url = "^1.4.0"
