[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
name = "relm"
version = "0.1.0"

[dependencies]
futures = "^0.1.10"
gtk = "^0.1.1"

[dependencies.relm-core]
path = "relm-core"

[dev-dependencies]
chrono = "^0.3.0"
gdk-pixbuf = "^0.1.1"
json = "^0.11.5"
tokio-core = "^0.1.4"
tokio-timer = "^0.1.0"
url = "^1.4.0"
