[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Asynchronous, GTK+-based, GUI library, inspired by Elm, written in Rust"
documentation = "https://docs.rs/relm/0.1.0/relm/"
license = "MIT"
name = "relm"
repository = "https://github.com/antoyo/relm"
version = "0.1.1-pre"

[features]
nightly = []

[dependencies]
futures = "^0.1.10"
glib = "^0.1.2"
glib-itc = "^0.1.1"
gtk = "^0.1.1"
log = "^0.3.7"

[dependencies.relm-core]
path = "relm-core"
version = "0.1.0"

[dev-dependencies]
base64 = "^0.4.0"
blake2 = "^0.4.0"
byteorder = "^1.0.0"
chrono = "^0.3.0"
gdk-pixbuf = "^0.1.1"
gdk-sys = "^0.3.3"
json = "^0.11.5"
rand = "^0.3.15"
simplelog = "^0.4.2"
tokio-core = "^0.1.4"
tokio-proto = "^0.1.0"
tokio-service = "^0.1.0"
twist = "^0.5.0"
url = "^1.4.0"

#[dev-dependencies.hyper]
#git = "https://github.com/hyperium/hyper"

#[dev-dependencies.hyper-tls]
#git = "https://github.com/hyperium/hyper-tls"

[dev-dependencies.relm-derive]
path = "relm-derive"
version = "0.1.0"
