[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Core streams and event loop primitives for asynchronous GUI in Rust. Foundation for the relm crate."
documentation = "https://docs.rs/relm-core/0.1.0/relm-core/"
license = "MIT"
name = "relm-core"
repository = "https://github.com/antoyo/relm"
version = "0.1.1-pre"

[dependencies]
futures = "^0.1.10"
glib-itc = "^0.1.1"
gtk = "^0.1.1"
tokio-core = "^0.1.4"

[dev-dependencies]
chrono = "^0.3.0"
glib = "^0.1.2"
