[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "relm-core"
version = "0.1.0"

[dependencies]
futures = "^0.1.10"
gtk = "^0.1.1"
lazy_static = "^0.2.2"
tokio-core = "^0.1.4"

[dev-dependencies]
chrono = "^0.3.0"
