[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Attributes to simplify the use of the relm crate"
documentation = "https://docs.rs/relm-attributes/"
license = "MIT"
name = "relm-attributes"
repository = "https://github.com/antoyo/relm"
version = "0.1.2-pre"

[dependencies]
quote = "^0.3.15"
relm-gen-widget = "^0.1.0"
syn = "^0.11.9"

[lib]
proc-macro = true
