[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "relm-attributes"
version = "0.1.0"

[dependencies]
lazy_static = "^0.2.4"
quote = "^0.3.15"

[dependencies.syn]
features = ["full"]
version = "^0.11.9"

[lib]
proc-macro = true
