[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Attributes to simplify the use of the relm crate"
documentation = "https://docs.rs/relm-attributes/"
license = "MIT"
name = "relm-attributes"
repository = "https://github.com/antoyo/relm"
version = "0.1.1"

[dependencies]
lazy_static = "^0.2.4"
quote = "^0.3.15"

[dependencies.syn]
features = ["fold", "full", "visit"]
version = "^0.11.9"

[lib]
proc-macro = true
