[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "relm-state"
version = "0.10.0"

[dependencies]
futures = "^0.1.14"
futures-glib = "^0.1.0"
log = "^0.3.7"

[dependencies.relm-core]
path = "../relm-core"
version = "^0.10.0"

[features]
use_impl_trait = []
