[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "buttons-derive"
version = "0.1.0"

[dependencies]
gtk = "^0.1.2"
relm-derive = "^0.1.2"

[dependencies.relm]
version = "^0.4.0"
default-features = false
