[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "buttons-derive"
version = "0.1.0"

[dependencies]
gtk = "^0.3.0"
relm = { path = "../.."}
relm-derive = { path = "../../relm-derive" }
