[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["development-tools::testing", "gui"]
description = "Testing library for relm"
documentation = "https://docs.rs/relm-test/"
license = "MIT"
name = "relm-test"
repository = "https://github.com/antoyo/relm"
version = "0.14.6"

[dependencies]
gtk-test = "^0.1"

[dependencies.relm-core]
path = "../relm-core"
version = "^0.14.0"
